import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import classNames from 'classnames'

import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, 'min-h-[100vh] flex flex-col')}>
        <Header/>

        <main className='container mx-auto flex-1 py-4'>
          {children}
        </main>

        <Footer/>
      </body>
    </html>
  )
}
