import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import classNames from 'classnames';

import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

import './globals.css';
import NavigationBar from '@/components/layout/NavigationBar';
import SideBar from '@/components/layout/SideBar';
import { ApolloProvider } from '@/lib/apolloProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          'min-h-[100vh] flex flex-col py-5 bg-gray-200'
        )}>
        <ApolloProvider>
          <Header />

          <main className="container mx-auto flex-1 py-4 flex">
            <NavigationBar />

            {children}

            <SideBar />
          </main>

          <Footer />
        </ApolloProvider>
      </body>
    </html>
  );
}
